sudo: false
language: erlang
script:
    - wget -c https://github.com/erlang/rebar3/releases/download/3.6.2/rebar3
    - chmod +x rebar3
    - REBAR3=./rebar3 make ci
otp_release:
    - 23.0.3
    - 22.3
    - 21.3
    - 20.3.8.22
